/* eslint-disable */
// @ts-nocheck
// This file is manually created to define the route tree
// In production, this would be auto-generated by TanStack Router CLI

import { Route as rootRoute } from './routes/__root'
import { Route as IndexRoute } from './routes/index'
import { Route as SignUpRoute } from './routes/sign-up'
import { Route as OnboardingRoute } from './routes/onboarding'
import { Route as CreateWorkspaceRoute } from './routes/create-workspace'
import { Route as InvitationsRoute } from './routes/invitations'
import { Route as WorkspaceInvitationsRoute } from './routes/workspace-invitations'
import { Route as ForgotPasswordRoute } from './routes/accounts/forgot-password'
import { Route as ResetPasswordRoute } from './routes/accounts/reset-password'
import { Route as SetPasswordRoute } from './routes/accounts/set-password'

// Declare module for type augmentation
declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRoute
      parentRoute: typeof rootRoute
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRoute
      parentRoute: typeof rootRoute
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRoute
      parentRoute: typeof rootRoute
    }
    '/create-workspace': {
      id: '/create-workspace'
      path: '/create-workspace'
      fullPath: '/create-workspace'
      preLoaderRoute: typeof CreateWorkspaceRoute
      parentRoute: typeof rootRoute
    }
    '/invitations': {
      id: '/invitations'
      path: '/invitations'
      fullPath: '/invitations'
      preLoaderRoute: typeof InvitationsRoute
      parentRoute: typeof rootRoute
    }
    '/workspace-invitations': {
      id: '/workspace-invitations'
      path: '/workspace-invitations'
      fullPath: '/workspace-invitations'
      preLoaderRoute: typeof WorkspaceInvitationsRoute
      parentRoute: typeof rootRoute
    }
    '/accounts/forgot-password': {
      id: '/accounts/forgot-password'
      path: '/accounts/forgot-password'
      fullPath: '/accounts/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRoute
      parentRoute: typeof rootRoute
    }
    '/accounts/reset-password': {
      id: '/accounts/reset-password'
      path: '/accounts/reset-password'
      fullPath: '/accounts/reset-password'
      preLoaderRoute: typeof ResetPasswordRoute
      parentRoute: typeof rootRoute
    }
    '/accounts/set-password': {
      id: '/accounts/set-password'
      path: '/accounts/set-password'
      fullPath: '/accounts/set-password'
      preLoaderRoute: typeof SetPasswordRoute
      parentRoute: typeof rootRoute
    }
    '/$workspaceSlug': {
      id: '/$workspaceSlug'
      path: '/$workspaceSlug'
      fullPath: '/$workspaceSlug'
      preLoaderRoute: typeof rootRoute
      parentRoute: typeof rootRoute
    }
  }
}

// Build route tree
const indexRoute = IndexRoute.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const signUpRoute = SignUpRoute.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRoute,
} as any)

const onboardingRoute = OnboardingRoute.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRoute,
} as any)

const createWorkspaceRoute = CreateWorkspaceRoute.update({
  id: '/create-workspace',
  path: '/create-workspace',
  getParentRoute: () => rootRoute,
} as any)

const invitationsRoute = InvitationsRoute.update({
  id: '/invitations',
  path: '/invitations',
  getParentRoute: () => rootRoute,
} as any)

const workspaceInvitationsRoute = WorkspaceInvitationsRoute.update({
  id: '/workspace-invitations',
  path: '/workspace-invitations',
  getParentRoute: () => rootRoute,
} as any)

const forgotPasswordRoute = ForgotPasswordRoute.update({
  id: '/accounts/forgot-password',
  path: '/accounts/forgot-password',
  getParentRoute: () => rootRoute,
} as any)

const resetPasswordRoute = ResetPasswordRoute.update({
  id: '/accounts/reset-password',
  path: '/accounts/reset-password',
  getParentRoute: () => rootRoute,
} as any)

const setPasswordRoute = SetPasswordRoute.update({
  id: '/accounts/set-password',
  path: '/accounts/set-password',
  getParentRoute: () => rootRoute,
} as any)

// Create the route tree
export const routeTree = rootRoute.addChildren([
  indexRoute,
  signUpRoute,
  onboardingRoute,
  createWorkspaceRoute,
  invitationsRoute,
  workspaceInvitationsRoute,
  forgotPasswordRoute,
  resetPasswordRoute,
  setPasswordRoute,
])
